map_processor:
  ros_parameters:
    raw_map_topic: "/raw_map_points"
    clustered_map_topic: "/clustered_map_points"
    timeout: 5
    min_cluster_size: 50
    min_samples: 1
    cluster_selection_epsilon: 0.5
    alpha: 1.3
